### ISSUE TITLE
Run keyboard.py example with IOError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by SMILElikeJONNY** [pimoroni/button-shim#11]
Hey,
when I run the keyboard.py example the following error happens: 

Traceback (most recent call last):
  File "keyboard.py", line 32, in <module>
    @buttonshim.on_press([buttonshim.BUTTON_A, buttonshim.BUTTON_B, buttonshim.BUTTON_C, buttonshim.BUTTON_D, buttonshim.BUTTON_E])
  File "/usr/lib/python2.7/dist-packages/buttonshim/__init__.py", line 294, in on_press
    setup()
  File "/usr/lib/python2.7/dist-packages/buttonshim/__init__.py", line 186, in setup
    _bus = smbus.SMBus(1)
IOError: [Errno 2] No such file or directory

Does anybody have an idea what the failure is?

**Comment by Gadgetoid** [comment]
You probably need to enable smbus. Run "Raspberry Pi Configuration" or `sudo raspi-config` on Terminal and enable it under Interfaces.

**Comment by SMILElikeJONNY** [comment]
yes thank you this was the solution.
