### ISSUE TITLE
Create example to illustrate use of `on_held` alongside other actions

### ISSUE THREAD

**Issue by Gadgetoid** [pimoroni/button-shim#13]
Since `on_held` triggers after `on_press`, and binding an action to `hold` and `press` events isn't intuitive or obvious, add an example to document how to accomplish this using a simple single-variable state monitor, and triggering the buttons primary (press) action within the release handler.

See: https://forums.pimoroni.com/t/button-shim-hold-issue/10157

**Comment by nthh** [comment]
I was having the same/similar issue when using on_release with on_hold. After releasing from the hold, it would trigger the release. 

My solution is to keep track of the time the last hold occurred and only fire the release handler if the last hold was more than 3 seconds ago (an arbitrary number but it works). Therefore, you won't trigger a release from the hold you just did. In addition, I never use on_press events but only on_release (as when will you be pressing but not releasing?).
