### ISSUE TITLE
README Install Steps Not Working after Buster Update

### ISSUE THREAD

**Issue by ogmosic** [pimoroni/button-shim#18]
Hello,
After doing a fresh install, using Buster image, and following your README instructions, the ButtonShim produces the following I/O error:

```
pi@rpiz-inky-phat:~/Pimoroni/button-shim/examples` $ python rainbow.py

Button SHIM: rainbow.py

Light up the LED a different colour of the rainbow with each button pressed.

Press Ctrl+C to exit.


Traceback (most recent call last):
File "rainbow.py", line 16, in <module>
  @buttonshim.on_press(buttonshim.BUTTON_A)
File "/usr/local/lib/python2.7/dist-packages/buttonshim/__init__.py", line 294, in on_press
  setup()
File "/usr/local/lib/python2.7/dist-packages/buttonshim/__init__.py", line 188, in setup
  _bus.write_byte_data(ADDR, REG_CONFIG, 0b00011111)
IOError: [Errno 121] Remote I/O error
pi@rpiz-inky-phat:~/Pimoroni/button-shim/examples $

```

**Comment by Gadgetoid** [comment]
This error would suggest a connection issue, try giving the SHIM a wiggle to make sure it's got a good connection to the GPIO pins.

**Comment by therhappy** [comment]
Hi!
Did @Gadgetoid 's answer provide a result? I'm encountering the same problem and can't find a position where the example works.

I'm using an inkyPHAT at the same time and it's working perfectly fine so I'd say the pins are quite securely attached.
