### ISSUE TITLE
Use buttons for Pi wakeup

### ISSUE THREAD

**Issue by andrewsiemer** [pimoroni/button-shim#20]
Shorting pins 5 and 6 (GPIO3 and GND) together will wake the Pi up from a halt state. Is there a way to use these buttons to do so?

Source:
https://howchoo.com/g/mwnlytk3zmm/how-to-add-a-power-button-to-your-raspberry-pi

**Comment by Gadgetoid** [comment]
I guess you could bodge it, but it would require some precise soldering. Definitely not something I'd want to attempt!
