### ISSUE TITLE
 button-shim/library/buttonshim/__init__.py has function definitions inside "while True:" loop

### ISSUE THREAD

**Issue by TheDiveO** [pimoroni/button-shim#5]
When browsing through `button-shim/library/buttonshim/__init__.py` to learn new tricks, I noticed something that looks odd to me, but I might be wrong here: near the end there's a "while True:" and this loop contains function definitions. Shouldn't these definitions go before the while loop?

**Comment by Gadgetoid** [comment]
Good spot. Yes they should. In their current location the functions are being re-defined and re-bound as handlers on Button SHIM over and over. This doesn't matter so much, since this code will only execute if you: ```python -m buttonshim``` but it should be fixed anyway.
